server:
  port: 3000
application:
  domain: cloudcheckr.us
  name: 'Annual BarkFest'
  logo: cloud.jpg
  favicon: cloud2.jpg
  numberOfRandomFakeUsers: 0
  showChallengeSolvedNotifications: true
  showChallengeHints: true
  showVersionNumber: true
  theme: slate # Options: cerulean  cosmo  cyborg  darkly  flatly lumen  paper  readable  sandstone  simplex  slate  spacelab  superhero  united  yeti
  gitHubRibbon: orange # Options: darkblue  gray  green  orange  red  white  none
  twitterUrl: 'https://twitter.com/cloudcheckr'
  facebookUrl: 'https://www.facebook.com/CloudCheckr'
  planetOverlayMap: orangemap2k.jpg
  planetName: Orangeuze
  recyclePage: 
    topProductImage: fruit_press.jpg
    bottomProductImage: apple_pressings.jpg
  altcoinName: Juicycoin
  cookieConsent: 
    backgroundColor: '#eb6c44'
    textColor: '#ffffff'
    buttonColor: '#f5d948'
    buttonTextColor: '#000000'
    message: 'This website uses fruit cookies to ensure you get the juiciest tracking experience.'
    dismissText: 'Me want it!'
    linkText: 'But me wait!'
    linkUrl: 'https://www.youtube.com/watch?v=9PnbKL3wuH4'
  securityTxt:
    contact: 'mailto:donotreply@owasp-juice.shop'
    encryption: 'https://keybase.io/bkimminich/pgp_keys.asc?fingerprint=19c01cb7157e4645e9e2c863062a85a8cbfbdcda'
    acknowledgements: '/#/score-board'
products:
  -
    name: 'Apple Juice (1000ml)'
    price: 1.99
    description: 'The all-time classic.'
    image: cc-dog-2.jpg
    reviews: # Options 'author': admin, jim, bender, ciso, support, morty, mc.safesearch
      - { text: 'One of my favorites!', author: admin }
  -
    name: 'Orange Juice (1000ml)'
    description: 'Made from oranges hand-picked by Uncle Dittmeyer.'
    price: 2.99
    image: cc-dog-14.jpg
  -
    name: 'Eggfruit Juice (500ml)'
    description: 'Now with even more exotic flavour.'
    price: 8.99
    image: cc-dog-23.jpg
    reviews:
      - { text: 'I bought it, would buy again. 5/7', author: admin }
  -
    name: 'Raspberry Juice (1000ml)'
    description: 'Made from blended Raspberry Pi, water and sugar.'
    price: 4.99
    image: cc-dog-26.jpg
  -
    name: 'Lemon Juice (500ml)'
    description: 'Sour but full of vitamins.'
    price: 2.99
    image: cc-dog-32.jpg
  -
    name: 'Banana Juice (1000ml)'
    description: 'Monkeys love it the most.'
    price: 1.99
    image: cc-dog-49.jpg
    reviews:
      - { text: 'Fry liked it too.', author: bender }
  -
    name: 'OWASP Juice Shop T-Shirt'
    description: 'Real fans wear it 24/7!'
    price: 22.49
    image: cc-dog-50.jpg
  -
    name: 'OWASP Juice Shop CTF Girlie-Shirt'
    description: 'For serious Capture-the-Flag heroines only!'
    price: 22.49
    image: cc-dog-58.jpg
  -
    name: 'OWASP SSL Advanced Forensic Tool (O-Saft)'
    description: 'O-Saft is an easy to use tool to show information about SSL certificate and tests the SSL connection according given list of ciphers and various SSL configurations.'
    price: 0.01
    image: cc-dog-63.jpg
    urlForProductTamperingChallenge: 'https://www.owasp.org/index.php/O-Saft'
  -
    name: 'Christmas Super-Surprise-Box (2014 Edition)'
    description: 'Contains a random selection of 10 bottles (each 500ml) of our tastiest juices and an extra fan shirt for an unbeatable price!'
    price: 29.99
    image: cc-dog-83.jpg
    useForChristmasSpecialChallenge: true
  -
    name: 'OWASP Juice Shop Sticker (2015/2016 design)'
    description: 'Die-cut sticker with the official 2015/2016 logo. By now this is a rare collectors item. <em>Out of stock!</em>'
    price: 999.99
    image: cc-dog-80.png
    deletedDate: '2017-04-28'
  -
    name: 'OWASP Juice Shop Iron-Ons (16pcs)'
    description: 'Upgrade your clothes with washer safe <a href="https://www.stickeryou.com/products/owasp-juice-shop/794" target="_blank">iron-ons</a> of the OWASP Juice Shop or CTF Extension logo!'
    price: 14.99
    image: cc-dog-78.jpg
  -
    name: 'OWASP Juice Shop Magnets (16pcs)'
    description: 'Your fridge will be even cooler with these OWASP Juice Shop or CTF Extension logo <a href="https://www.stickeryou.com/products/owasp-juice-shop/794" target="_blank">magnets</a>!'
    price: 15.99
    image: cc-dog-75.jpg
  -
    name: 'OWASP Juice Shop Sticker Page'
    description: 'Massive decoration opportunities with these OWASP Juice Shop or CTF Extension <a href="https://www.stickeryou.com/products/owasp-juice-shop/794" target="_blank">sticker pages</a>! Each page has 16 stickers on it.'
    price: 9.99
    image: download2.jpg
  -
    name: 'OWASP Juice Shop Sticker Single'
    description: 'Super high-quality vinyl <a href="https://www.stickeryou.com/products/owasp-juice-shop/794" target="_blank">sticker single</a> with the OWASP Juice Shop or CTF Extension logo! The ultimate laptop decal!'
    price: 4.99
    image: download.jpg
  -
    name: 'OWASP Juice Shop Temporay Tattoos (16pcs)'
    description: 'Get one of these <a href="https://www.stickeryou.com/products/owasp-juice-shop/794" target="_blank">temporary tattoos</a> to proudly wear the OWASP Juice Shop or CTF Extension logo on your skin! If you tweet a photo of yourself with the tattoo, you get a couple of our stickers for free! Please mention <a href="https://twitter.com/owasp_juiceshop" target="_blank"><code>@owasp_juiceshop</code></a> in your tweet!'
    price: 14.99
    image: download1.jpg
    reviews:
      - { text: 'I straight-up gots nuff props fo''these tattoos!', author: mc.safesearch }
  -
    name: 'OWASP Juice Shop Mug'
    description: 'Black mug with regular logo on one side and CTF logo on the other! Your colleagues will envy you!'
    price: 21.99
    image: cc-dog-69.jpg
  -
    name: 'OWASP Juice Shop Hoodie'
    description: 'Mr. Robot-style apparel. But in black. And with logo.'
    price: 49.99
    image: cc-dog-91.jpg
  -
    name: 'OWASP Juice Shop-CTF Velcro Patch'
    description: '4x3.5" embroidered patch with velcro backside. The ultimate decal for every tactical bag or backpack!'
    price: 2.92
    image: Allstar1.png
    reviews:
      - { text: 'This thang would look phat on Bobby''s jacked fur coat!', author: mc.safesearch }
      - { text: 'Looks so much better on my uniform than the boring Starfleet symbol.', author: jim }
  -
    name: 'Woodruff Syrup "Forest Master X-Treme"'
    description: 'Harvested and manufactured in the Black Forest, Germany. Can cause hyperactive behavior in children. Can cause permanent green tongue when consumed undiluted.'
    price: 6.99
    image: cc-dog-18.jpg
  -
    name: 'Green Smoothie'
    description: 'Looks poisonous but is actually very good for your health! Made from green cabbage, spinach, kiwi and grass.'
    price: 1.99
    image: cc-dog-29.jpg
    reviews:
      - { text: 'Fresh out of a replicator.', author: jim }
  -
    name: 'Quince Juice (1000ml)'
    description: 'Juice of the <em>Cydonia oblonga</em> fruit. Not exactly sweet but rich in Vitamin C.'
    price: 4.99
    image: cc-dog-38.jpg
  -
    name: 'Apple Pomace'
    description: 'Finest pressings of apples. Allergy disclaimer: Might contain traces of worms. Can be <a href="/#recycle">sent back to us</a> for recycling.'
    price: 0.89
    image: cc-dog-53.jpg
  -
    name: 'Fruit Press'
    description: 'Fruits go in. Juice comes out. Pomace you can send back to us for recycling purposes.'
    price: 89.99
    image: cc-dog-66.jpg
  -
    name: 'OWASP Juice Shop Logo (3D-printed)'
    description: 'This rare item was designed and handcrafted in Sweden. This is why it is so incredibly expensive despite its complete lack of purpose.'
    price: 99.99
    image: 3d_keychain.jpg # Exif metadata contains "OpenSCAD" as subtle hint...
    fileForRetrieveBlueprintChallenge: JuiceShop.stl # ...to blueprint file type
  -
    name: 'Juice Shop Artwork'
    description: 'Unique masterpiece painted with different kinds of juice on 90g/m² lined paper.'
    price: 278.74
    image: cc-business-card.png
  -
    name: 'Global OWASP WASPY Award 2017 Nomnation'
    description: 'Your chance to nominate up to three quiet pillars of the OWASP community ends 2017-06-30! <a href="https://www.owasp.org/index.php/WASPY_Awards_2017">Nominate now!</a>'
    price: 0.03
    image: aws.png
    deletedDate: '2017-07-01'
  -
    name: 'Strawberry Juice (500ml)'
    description: 'Sweet & tasty!'
    price: 3.99
    image: cc-dog-60.jpg
  -
    name: 'Carrot Juice (1000ml)'
    description: 'As the old German saying goes: "Carrots are good for the eyes. Or has anyone ever seen a rabbit with glasses?"'
    price: 2.99
    image: cc-dog-70.jpg
  -
    name: 'OWASP Juice Shop Sweden Tour 2017 Sticker Sheet (Special Edition)'
    description: '10 sheets of Sweden-themed stickers with 15 stickers on each.'
    price: 19.1
    image: cc-dog-71.jpg
    deletedDate: '2017-09-20'
  -
    name: 'Pwning OWASP Juice Shop'
    description: '<em>The official Companion Guide</em> by Björn Kimminich available <a href="https://leanpub.com/juice-shop">for free on LeanPub</a> and <a href="https://bkimminich.gitbooks.io/pwning-owasp-juice-shop/content/">readable online on GitBook</a>!'
    price: 5.99
    image: cc-dog-74.jpg
    reviews:
      - { text: 'Even more interesting than watching Interdimensional Cable!', author: morty }
  -
    name: 'Melon Bike (Comeback-Product 2018 Edition)'
    description: 'The wheels of this bicycle are made from real water melons. You might not want to ride it up/down the curb too hard.'
    price: 2999
    image: cc-dog-89.jpg
ctf:
  countryMapping: ~
  showFlagsInNotifications: false
  showCountryDetailsInNotifications: none # Options: none  name  flag  both